// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC53xTT_jI3N8PChWZRGbXHHcncLYl7ZhE',
    appId: '1:184093741702:web:0bda09889345f21d9d3707',
    messagingSenderId: '184093741702',
    projectId: 'icthub-2024-604ca',
    authDomain: 'icthub-2024-604ca.firebaseapp.com',
    storageBucket: 'icthub-2024-604ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsuFlEo-whJ2LNyb-uJbeFiiCAi5zDlAQ',
    appId: '1:184093741702:android:e840d7db2ff67dbb9d3707',
    messagingSenderId: '184093741702',
    projectId: 'icthub-2024-604ca',
    storageBucket: 'icthub-2024-604ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAST9xNeZXhwQkMAx-gc0UDqGw67deYVtU',
    appId: '1:184093741702:ios:41dcd1af8e83413f9d3707',
    messagingSenderId: '184093741702',
    projectId: 'icthub-2024-604ca',
    storageBucket: 'icthub-2024-604ca.appspot.com',
    iosBundleId: 'com.example.apiproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAST9xNeZXhwQkMAx-gc0UDqGw67deYVtU',
    appId: '1:184093741702:ios:41dcd1af8e83413f9d3707',
    messagingSenderId: '184093741702',
    projectId: 'icthub-2024-604ca',
    storageBucket: 'icthub-2024-604ca.appspot.com',
    iosBundleId: 'com.example.apiproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC53xTT_jI3N8PChWZRGbXHHcncLYl7ZhE',
    appId: '1:184093741702:web:570978e3cb1bb59c9d3707',
    messagingSenderId: '184093741702',
    projectId: 'icthub-2024-604ca',
    authDomain: 'icthub-2024-604ca.firebaseapp.com',
    storageBucket: 'icthub-2024-604ca.appspot.com',
  );
}
